name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        
      - name: Get Changed Files
        id: get_changed_files
        run: |
          changed_files=""
          for file in "${{ github.event.commits[0].added }}"; do
            changed_files="${changed_files}${file}"$'\n'
          done
          for file in "${{ github.event.commits[0].modified }}"; do
            changed_files="${changed_files}${file}"$'\n'
          done
          echo "CHANGED_FILES=$changed_files" >> $GITHUB_ENV
      
      - name: Print Changed Files
        run: |
          changed_files="${{ env.CHANGED_FILES }}"
          echo "Changed files: $changed_files"
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'
      
      - name: Run Python Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pip install openai=='1.14.1'
          python translator.py "${{ steps.get_changed_files.outputs.changed_files }}"

      - name: Commit Changes
        run: |
          git config --global user.email tkdgns0917@gmail.com
          git config --global user.name sangho0n_remote
          git add .
          git commit -m "Add new files transalted by OpenAI"
      
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.97.0"

      - name: Build
        run: hugo -t hugo-theme-stack

      - name: Deploy
        run: |
          cd public
          git checkout main
          git add .
          msg="rebuilding site `date`"
          if [ $# -eq 1 ]
          then 
            msg="$1"
          fi
          git commit -m "$msg"
          git push origin main
