name: Get Pushed Files

on:
  push:
    branches:
      - main

jobs:
  get_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Get Changed Files
        id: get_changed_files
        run: |
          echo "::set-output name=changed_files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
      
      - name: Print Changed Files
        run: |
          changed_files="${{ steps.get_changed_files.outputs.changed_files }}"
          echo "Changed files: $changed_files"
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'
          
      - name: Install dependencies
        run: pip install openai==1.14.1
      
      - name: Run Python Script
        run: |
          python translator.py "${{ steps.get_changed_files.outputs.changed_files }}"
