name: CI
on: push
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        
      - name: Get Changed Files
        id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          changed_files=""
          for file in ${{ steps.files.outputs.added_modified }}; do
            changed_files="${changed_files}${file}"$'\n'
            echo "Changed file: $file"
          done
          echo "$changed_files" > changed_files.txt
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'
      
      - name: Run Python Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pip install openai=='1.14.1'
          changed_files=$(cat changed_files.txt)
          echo "Changed files: $changed_files"
          python -u translator.py $changed_files
          rm changed_files.txt

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: "0.123.8"
          extended: true

      - name: Build
        run: |
          hugo -t hugo-theme-stack

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: sangho0n/sangho0n.github.io
          publish_branch: main  # default: gh-pages
          publish_dir: ./public

      - name: Commit added files
        uses: EndBug/add-and-commit@v9.1.4
        with:
        author_name: Author Name
        author_email: mail@example.com
        push: true
        